<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="Verify" />
    <PackageReference Include="Sbom" PrivateAssets="all" />
  </ItemGroup>
</Project>